/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Url = IDL.Text;
export const GalleryImageInput = IDL.Record({
  'year' : IDL.Nat,
  'imageUrl' : Url,
  'caption' : IDL.Text,
  'eventName' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'year' : IDL.Nat,
  'imageUrl' : Url,
  'caption' : IDL.Text,
  'eventName' : IDL.Text,
});
export const PublicationType = IDL.Variant({
  'book' : IDL.Null,
  'paper' : IDL.Null,
});
export const PublicationInput = IDL.Record({
  'coverImageUrl' : Url,
  'title' : IDL.Text,
  'purchaseLink' : Url,
  'isbn' : IDL.Text,
  'publisher' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'pubType' : PublicationType,
});
export const Publication = IDL.Record({
  'id' : IDL.Nat,
  'coverImageUrl' : Url,
  'title' : IDL.Text,
  'purchaseLink' : Url,
  'isbn' : IDL.Text,
  'publisher' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'pubType' : PublicationType,
});
export const ResearchType = IDL.Variant({
  'article' : IDL.Null,
  'paper' : IDL.Null,
});
export const ResearchInput = IDL.Record({
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'year' : IDL.Nat,
  'resType' : ResearchType,
  'pdfUrl' : Url,
  'abstract' : IDL.Text,
  'coAuthors' : IDL.Vec(IDL.Text),
});
export const Research = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'year' : IDL.Nat,
  'resType' : ResearchType,
  'pdfUrl' : Url,
  'abstract' : IDL.Text,
  'coAuthors' : IDL.Vec(IDL.Text),
});
export const TimelineCategory = IDL.Variant({
  'award' : IDL.Null,
  'career' : IDL.Null,
  'publication' : IDL.Null,
});
export const TimelineEntryInput = IDL.Record({
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'category' : TimelineCategory,
});
export const TimelineEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'category' : TimelineCategory,
});
export const Timestamp = IDL.Int;
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ContactMessageInput = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGalleryImage' : IDL.Func([GalleryImageInput], [GalleryImage], []),
  'addPublication' : IDL.Func([PublicationInput], [Publication], []),
  'addResearch' : IDL.Func([ResearchInput], [Research], []),
  'addTimelineEntry' : IDL.Func([TimelineEntryInput], [TimelineEntry], []),
  'deleteContactMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGalleryImage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePublication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteResearch' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTimelineEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getGalleryImage' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryImage)], ['query']),
  'getPublication' : IDL.Func([IDL.Nat], [IDL.Opt(Publication)], ['query']),
  'getResearch' : IDL.Func([IDL.Nat], [IDL.Opt(Research)], ['query']),
  'getTimelineEntry' : IDL.Func([IDL.Nat], [IDL.Opt(TimelineEntry)], ['query']),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'listPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
  'listResearch' : IDL.Func([], [IDL.Vec(Research)], ['query']),
  'listTimelineEntries' : IDL.Func([], [IDL.Vec(TimelineEntry)], ['query']),
  'submitContactMessage' : IDL.Func(
      [ContactMessageInput],
      [ContactMessage],
      [],
    ),
  'updateGalleryImage' : IDL.Func(
      [IDL.Nat, GalleryImageInput],
      [IDL.Opt(GalleryImage)],
      [],
    ),
  'updatePublication' : IDL.Func(
      [IDL.Nat, PublicationInput],
      [IDL.Opt(Publication)],
      [],
    ),
  'updateResearch' : IDL.Func(
      [IDL.Nat, ResearchInput],
      [IDL.Opt(Research)],
      [],
    ),
  'updateTimelineEntry' : IDL.Func(
      [IDL.Nat, TimelineEntryInput],
      [IDL.Opt(TimelineEntry)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Url = IDL.Text;
  const GalleryImageInput = IDL.Record({
    'year' : IDL.Nat,
    'imageUrl' : Url,
    'caption' : IDL.Text,
    'eventName' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'year' : IDL.Nat,
    'imageUrl' : Url,
    'caption' : IDL.Text,
    'eventName' : IDL.Text,
  });
  const PublicationType = IDL.Variant({
    'book' : IDL.Null,
    'paper' : IDL.Null,
  });
  const PublicationInput = IDL.Record({
    'coverImageUrl' : Url,
    'title' : IDL.Text,
    'purchaseLink' : Url,
    'isbn' : IDL.Text,
    'publisher' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'pubType' : PublicationType,
  });
  const Publication = IDL.Record({
    'id' : IDL.Nat,
    'coverImageUrl' : Url,
    'title' : IDL.Text,
    'purchaseLink' : Url,
    'isbn' : IDL.Text,
    'publisher' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'pubType' : PublicationType,
  });
  const ResearchType = IDL.Variant({
    'article' : IDL.Null,
    'paper' : IDL.Null,
  });
  const ResearchInput = IDL.Record({
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'year' : IDL.Nat,
    'resType' : ResearchType,
    'pdfUrl' : Url,
    'abstract' : IDL.Text,
    'coAuthors' : IDL.Vec(IDL.Text),
  });
  const Research = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'year' : IDL.Nat,
    'resType' : ResearchType,
    'pdfUrl' : Url,
    'abstract' : IDL.Text,
    'coAuthors' : IDL.Vec(IDL.Text),
  });
  const TimelineCategory = IDL.Variant({
    'award' : IDL.Null,
    'career' : IDL.Null,
    'publication' : IDL.Null,
  });
  const TimelineEntryInput = IDL.Record({
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'category' : TimelineCategory,
  });
  const TimelineEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'category' : TimelineCategory,
  });
  const Timestamp = IDL.Int;
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ContactMessageInput = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addGalleryImage' : IDL.Func([GalleryImageInput], [GalleryImage], []),
    'addPublication' : IDL.Func([PublicationInput], [Publication], []),
    'addResearch' : IDL.Func([ResearchInput], [Research], []),
    'addTimelineEntry' : IDL.Func([TimelineEntryInput], [TimelineEntry], []),
    'deleteContactMessage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGalleryImage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePublication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteResearch' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTimelineEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getGalleryImage' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryImage)], ['query']),
    'getPublication' : IDL.Func([IDL.Nat], [IDL.Opt(Publication)], ['query']),
    'getResearch' : IDL.Func([IDL.Nat], [IDL.Opt(Research)], ['query']),
    'getTimelineEntry' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TimelineEntry)],
        ['query'],
      ),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'listPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
    'listResearch' : IDL.Func([], [IDL.Vec(Research)], ['query']),
    'listTimelineEntries' : IDL.Func([], [IDL.Vec(TimelineEntry)], ['query']),
    'submitContactMessage' : IDL.Func(
        [ContactMessageInput],
        [ContactMessage],
        [],
      ),
    'updateGalleryImage' : IDL.Func(
        [IDL.Nat, GalleryImageInput],
        [IDL.Opt(GalleryImage)],
        [],
      ),
    'updatePublication' : IDL.Func(
        [IDL.Nat, PublicationInput],
        [IDL.Opt(Publication)],
        [],
      ),
    'updateResearch' : IDL.Func(
        [IDL.Nat, ResearchInput],
        [IDL.Opt(Research)],
        [],
      ),
    'updateTimelineEntry' : IDL.Func(
        [IDL.Nat, TimelineEntryInput],
        [IDL.Opt(TimelineEntry)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };