/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface ContactMessageInput {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface GalleryImage {
  'id' : bigint,
  'year' : bigint,
  'imageUrl' : Url,
  'caption' : string,
  'eventName' : string,
}
export interface GalleryImageInput {
  'year' : bigint,
  'imageUrl' : Url,
  'caption' : string,
  'eventName' : string,
}
export interface Publication {
  'id' : bigint,
  'coverImageUrl' : Url,
  'title' : string,
  'purchaseLink' : Url,
  'isbn' : string,
  'publisher' : string,
  'year' : bigint,
  'description' : string,
  'pubType' : PublicationType,
}
export interface PublicationInput {
  'coverImageUrl' : Url,
  'title' : string,
  'purchaseLink' : Url,
  'isbn' : string,
  'publisher' : string,
  'year' : bigint,
  'description' : string,
  'pubType' : PublicationType,
}
export type PublicationType = { 'book' : null } |
  { 'paper' : null };
export interface Research {
  'id' : bigint,
  'title' : string,
  'venue' : string,
  'year' : bigint,
  'resType' : ResearchType,
  'pdfUrl' : Url,
  'abstract' : string,
  'coAuthors' : Array<string>,
}
export interface ResearchInput {
  'title' : string,
  'venue' : string,
  'year' : bigint,
  'resType' : ResearchType,
  'pdfUrl' : Url,
  'abstract' : string,
  'coAuthors' : Array<string>,
}
export type ResearchType = { 'article' : null } |
  { 'paper' : null };
export type TimelineCategory = { 'award' : null } |
  { 'career' : null } |
  { 'publication' : null };
export interface TimelineEntry {
  'id' : bigint,
  'title' : string,
  'year' : bigint,
  'description' : string,
  'category' : TimelineCategory,
}
export interface TimelineEntryInput {
  'title' : string,
  'year' : bigint,
  'description' : string,
  'category' : TimelineCategory,
}
export type Timestamp = bigint;
export type Url = string;
export interface _SERVICE {
  'addGalleryImage' : ActorMethod<[GalleryImageInput], GalleryImage>,
  'addPublication' : ActorMethod<[PublicationInput], Publication>,
  'addResearch' : ActorMethod<[ResearchInput], Research>,
  'addTimelineEntry' : ActorMethod<[TimelineEntryInput], TimelineEntry>,
  'deleteContactMessage' : ActorMethod<[bigint], boolean>,
  'deleteGalleryImage' : ActorMethod<[bigint], boolean>,
  'deletePublication' : ActorMethod<[bigint], boolean>,
  'deleteResearch' : ActorMethod<[bigint], boolean>,
  'deleteTimelineEntry' : ActorMethod<[bigint], boolean>,
  'getGalleryImage' : ActorMethod<[bigint], [] | [GalleryImage]>,
  'getPublication' : ActorMethod<[bigint], [] | [Publication]>,
  'getResearch' : ActorMethod<[bigint], [] | [Research]>,
  'getTimelineEntry' : ActorMethod<[bigint], [] | [TimelineEntry]>,
  'listContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'listGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'listPublications' : ActorMethod<[], Array<Publication>>,
  'listResearch' : ActorMethod<[], Array<Research>>,
  'listTimelineEntries' : ActorMethod<[], Array<TimelineEntry>>,
  'submitContactMessage' : ActorMethod<[ContactMessageInput], ContactMessage>,
  'updateGalleryImage' : ActorMethod<
    [bigint, GalleryImageInput],
    [] | [GalleryImage]
  >,
  'updatePublication' : ActorMethod<
    [bigint, PublicationInput],
    [] | [Publication]
  >,
  'updateResearch' : ActorMethod<[bigint, ResearchInput], [] | [Research]>,
  'updateTimelineEntry' : ActorMethod<
    [bigint, TimelineEntryInput],
    [] | [TimelineEntry]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];