/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ResearchInput {
    title: string;
    venue: string;
    year: bigint;
    resType: ResearchType;
    pdfUrl: Url;
    abstract: string;
    coAuthors: Array<string>;
}
export type Timestamp = bigint;
export interface PublicationInput {
    coverImageUrl: Url;
    title: string;
    purchaseLink: Url;
    isbn: string;
    publisher: string;
    year: bigint;
    description: string;
    pubType: PublicationType;
}
export interface TimelineEntry {
    id: bigint;
    title: string;
    year: bigint;
    description: string;
    category: TimelineCategory;
}
export type Url = string;
export interface ContactMessage {
    id: bigint;
    subject: string;
    name: string;
    email: string;
    message: string;
    timestamp: Timestamp;
}
export interface ContactMessageInput {
    subject: string;
    name: string;
    email: string;
    message: string;
}
export interface GalleryImage {
    id: bigint;
    year: bigint;
    imageUrl: Url;
    caption: string;
    eventName: string;
}
export interface Publication {
    id: bigint;
    coverImageUrl: Url;
    title: string;
    purchaseLink: Url;
    isbn: string;
    publisher: string;
    year: bigint;
    description: string;
    pubType: PublicationType;
}
export interface Research {
    id: bigint;
    title: string;
    venue: string;
    year: bigint;
    resType: ResearchType;
    pdfUrl: Url;
    abstract: string;
    coAuthors: Array<string>;
}
export interface GalleryImageInput {
    year: bigint;
    imageUrl: Url;
    caption: string;
    eventName: string;
}
export interface TimelineEntryInput {
    title: string;
    year: bigint;
    description: string;
    category: TimelineCategory;
}
export enum PublicationType {
    book = "book",
    paper = "paper"
}
export enum ResearchType {
    article = "article",
    paper = "paper"
}
export enum TimelineCategory {
    award = "award",
    career = "career",
    publication = "publication"
}
export interface backendInterface {
    addGalleryImage(input: GalleryImageInput): Promise<GalleryImage>;
    addPublication(input: PublicationInput): Promise<Publication>;
    addResearch(input: ResearchInput): Promise<Research>;
    addTimelineEntry(input: TimelineEntryInput): Promise<TimelineEntry>;
    deleteContactMessage(id: bigint): Promise<boolean>;
    deleteGalleryImage(id: bigint): Promise<boolean>;
    deletePublication(id: bigint): Promise<boolean>;
    deleteResearch(id: bigint): Promise<boolean>;
    deleteTimelineEntry(id: bigint): Promise<boolean>;
    getGalleryImage(id: bigint): Promise<GalleryImage | null>;
    getPublication(id: bigint): Promise<Publication | null>;
    getResearch(id: bigint): Promise<Research | null>;
    getTimelineEntry(id: bigint): Promise<TimelineEntry | null>;
    listContactMessages(): Promise<Array<ContactMessage>>;
    listGalleryImages(): Promise<Array<GalleryImage>>;
    listPublications(): Promise<Array<Publication>>;
    listResearch(): Promise<Array<Research>>;
    listTimelineEntries(): Promise<Array<TimelineEntry>>;
    submitContactMessage(input: ContactMessageInput): Promise<ContactMessage>;
    updateGalleryImage(id: bigint, input: GalleryImageInput): Promise<GalleryImage | null>;
    updatePublication(id: bigint, input: PublicationInput): Promise<Publication | null>;
    updateResearch(id: bigint, input: ResearchInput): Promise<Research | null>;
    updateTimelineEntry(id: bigint, input: TimelineEntryInput): Promise<TimelineEntry | null>;
}
import type { GalleryImage as _GalleryImage, Publication as _Publication, PublicationInput as _PublicationInput, PublicationType as _PublicationType, Research as _Research, ResearchInput as _ResearchInput, ResearchType as _ResearchType, TimelineCategory as _TimelineCategory, TimelineEntry as _TimelineEntry, TimelineEntryInput as _TimelineEntryInput, Url as _Url } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGalleryImage(arg0: GalleryImageInput): Promise<GalleryImage> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(arg0);
            return result;
        }
    }
    async addPublication(arg0: PublicationInput): Promise<Publication> {
        if (this.processError) {
            try {
                const result = await this.actor.addPublication(to_candid_PublicationInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Publication_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPublication(to_candid_PublicationInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Publication_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addResearch(arg0: ResearchInput): Promise<Research> {
        if (this.processError) {
            try {
                const result = await this.actor.addResearch(to_candid_ResearchInput_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Research_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResearch(to_candid_ResearchInput_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Research_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTimelineEntry(arg0: TimelineEntryInput): Promise<TimelineEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addTimelineEntry(to_candid_TimelineEntryInput_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TimelineEntry_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTimelineEntry(to_candid_TimelineEntryInput_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TimelineEntry_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteContactMessage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactMessage(arg0);
            return result;
        }
    }
    async deleteGalleryImage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deletePublication(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePublication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePublication(arg0);
            return result;
        }
    }
    async deleteResearch(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResearch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResearch(arg0);
            return result;
        }
    }
    async deleteTimelineEntry(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTimelineEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTimelineEntry(arg0);
            return result;
        }
    }
    async getGalleryImage(arg0: bigint): Promise<GalleryImage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImage(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImage(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublication(arg0: bigint): Promise<Publication | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublication(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublication(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResearch(arg0: bigint): Promise<Research | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearch(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearch(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimelineEntry(arg0: bigint): Promise<TimelineEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimelineEntry(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimelineEntry(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactMessages();
            return result;
        }
    }
    async listGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryImages();
            return result;
        }
    }
    async listPublications(): Promise<Array<Publication>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublications();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublications();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listResearch(): Promise<Array<Research>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResearch();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResearch();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTimelineEntries(): Promise<Array<TimelineEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTimelineEntries();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTimelineEntries();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactMessage(arg0: ContactMessageInput): Promise<ContactMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0);
            return result;
        }
    }
    async updateGalleryImage(arg0: bigint, arg1: GalleryImageInput): Promise<GalleryImage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryImage(arg0, arg1);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryImage(arg0, arg1);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePublication(arg0: bigint, arg1: PublicationInput): Promise<Publication | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublication(arg0, to_candid_PublicationInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublication(arg0, to_candid_PublicationInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateResearch(arg0: bigint, arg1: ResearchInput): Promise<Research | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResearch(arg0, to_candid_ResearchInput_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResearch(arg0, to_candid_ResearchInput_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTimelineEntry(arg0: bigint, arg1: TimelineEntryInput): Promise<TimelineEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTimelineEntry(arg0, to_candid_TimelineEntryInput_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTimelineEntry(arg0, to_candid_TimelineEntryInput_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PublicationType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicationType): PublicationType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Publication_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Publication): Publication {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ResearchType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResearchType): ResearchType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Research_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Research): Research {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TimelineCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineCategory): TimelineCategory {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TimelineEntry_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineEntry): TimelineEntry {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GalleryImage]): GalleryImage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Publication]): Publication | null {
    return value.length === 0 ? null : from_candid_Publication_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Research]): Research | null {
    return value.length === 0 ? null : from_candid_Research_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TimelineEntry]): TimelineEntry | null {
    return value.length === 0 ? null : from_candid_TimelineEntry_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    venue: string;
    year: bigint;
    resType: _ResearchType;
    pdfUrl: _Url;
    abstract: string;
    coAuthors: Array<string>;
}): {
    id: bigint;
    title: string;
    venue: string;
    year: bigint;
    resType: ResearchType;
    pdfUrl: Url;
    abstract: string;
    coAuthors: Array<string>;
} {
    return {
        id: value.id,
        title: value.title,
        venue: value.venue,
        year: value.year,
        resType: from_candid_ResearchType_n15(_uploadFile, _downloadFile, value.resType),
        pdfUrl: value.pdfUrl,
        abstract: value.abstract,
        coAuthors: value.coAuthors
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    year: bigint;
    description: string;
    category: _TimelineCategory;
}): {
    id: bigint;
    title: string;
    year: bigint;
    description: string;
    category: TimelineCategory;
} {
    return {
        id: value.id,
        title: value.title,
        year: value.year,
        description: value.description,
        category: from_candid_TimelineCategory_n23(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    coverImageUrl: _Url;
    title: string;
    purchaseLink: _Url;
    isbn: string;
    publisher: string;
    year: bigint;
    description: string;
    pubType: _PublicationType;
}): {
    id: bigint;
    coverImageUrl: Url;
    title: string;
    purchaseLink: Url;
    isbn: string;
    publisher: string;
    year: bigint;
    description: string;
    pubType: PublicationType;
} {
    return {
        id: value.id,
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        purchaseLink: value.purchaseLink,
        isbn: value.isbn,
        publisher: value.publisher,
        year: value.year,
        description: value.description,
        pubType: from_candid_PublicationType_n7(_uploadFile, _downloadFile, value.pubType)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    article: null;
} | {
    paper: null;
}): ResearchType {
    return "article" in value ? ResearchType.article : "paper" in value ? ResearchType.paper : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    award: null;
} | {
    career: null;
} | {
    publication: null;
}): TimelineCategory {
    return "award" in value ? TimelineCategory.award : "career" in value ? TimelineCategory.career : "publication" in value ? TimelineCategory.publication : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    book: null;
} | {
    paper: null;
}): PublicationType {
    return "book" in value ? PublicationType.book : "paper" in value ? PublicationType.paper : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Publication>): Array<Publication> {
    return value.map((x)=>from_candid_Publication_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Research>): Array<Research> {
    return value.map((x)=>from_candid_Research_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimelineEntry>): Array<TimelineEntry> {
    return value.map((x)=>from_candid_TimelineEntry_n21(_uploadFile, _downloadFile, x));
}
function to_candid_PublicationInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationInput): _PublicationInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PublicationType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationType): _PublicationType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ResearchInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResearchInput): _ResearchInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ResearchType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResearchType): _ResearchType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_TimelineCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimelineCategory): _TimelineCategory {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_TimelineEntryInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimelineEntryInput): _TimelineEntryInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    venue: string;
    year: bigint;
    resType: ResearchType;
    pdfUrl: Url;
    abstract: string;
    coAuthors: Array<string>;
}): {
    title: string;
    venue: string;
    year: bigint;
    resType: _ResearchType;
    pdfUrl: _Url;
    abstract: string;
    coAuthors: Array<string>;
} {
    return {
        title: value.title,
        venue: value.venue,
        year: value.year,
        resType: to_candid_ResearchType_n11(_uploadFile, _downloadFile, value.resType),
        pdfUrl: value.pdfUrl,
        abstract: value.abstract,
        coAuthors: value.coAuthors
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    year: bigint;
    description: string;
    category: TimelineCategory;
}): {
    title: string;
    year: bigint;
    description: string;
    category: _TimelineCategory;
} {
    return {
        title: value.title,
        year: value.year,
        description: value.description,
        category: to_candid_TimelineCategory_n19(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coverImageUrl: Url;
    title: string;
    purchaseLink: Url;
    isbn: string;
    publisher: string;
    year: bigint;
    description: string;
    pubType: PublicationType;
}): {
    coverImageUrl: _Url;
    title: string;
    purchaseLink: _Url;
    isbn: string;
    publisher: string;
    year: bigint;
    description: string;
    pubType: _PublicationType;
} {
    return {
        coverImageUrl: value.coverImageUrl,
        title: value.title,
        purchaseLink: value.purchaseLink,
        isbn: value.isbn,
        publisher: value.publisher,
        year: value.year,
        description: value.description,
        pubType: to_candid_PublicationType_n3(_uploadFile, _downloadFile, value.pubType)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResearchType): {
    article: null;
} | {
    paper: null;
} {
    return value == ResearchType.article ? {
        article: null
    } : value == ResearchType.paper ? {
        paper: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimelineCategory): {
    award: null;
} | {
    career: null;
} | {
    publication: null;
} {
    return value == TimelineCategory.award ? {
        award: null
    } : value == TimelineCategory.career ? {
        career: null
    } : value == TimelineCategory.publication ? {
        publication: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationType): {
    book: null;
} | {
    paper: null;
} {
    return value == PublicationType.book ? {
        book: null
    } : value == PublicationType.paper ? {
        paper: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
